name: "package"
version: "1.0.0"
config-version: 2

profile: "package"

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "dbt_packages"
